### PR TITLE
18 chart view

### PR DESCRIPTION
**Pull request by maciej-zarzeczny**
**Changes**

- Switched MUI styled engine from `styled-components` to `emotion`
- Uninstalled `craco` as it was causing issues with hot reloading
- Updated dependencies 
- Cleaned up some styles 
- Cleaned up `MapPopup` component as we weren't using most of things in there (those were left overs from Covid-19 map)
- Create `ChartView` component
- Chart is showing dynamic data based on selected country from the Sidebar
- It is possible to change chart time period using the Slider component
- Slider range changes to show only available data for selected country
- Added Cypress tests

### CODE REVIEW

**Review by OskarKocjan — APPROVED** [review]
Great work!💯

**Review by OskarKocjan — CHANGES_REQUESTED** [review]
Everything looks great 💯 There is just one small error. When you chose the "WorldWide" option from the drop-down menu and then change view to Country view the error occurs. It is probably because when you select this option, the `selectedCountry` variable is no longer null (it is object {name: "worldwide"}).

**Comment by maciej-zarzeczny** [comment]
@OskarKocjan Great catch! Didn't thought of that, I will fix this shortly

**Review by OskarKocjan — APPROVED** [review]
LGTM!

**Pull request merged**
